<?php namespace AnitMsg;
 use pocketmine\plugin\PluginBase;
 use pocketmine\Server;
 use pocketmine\event\Listener;
 use pocketmine\utils\TextFormat as F;
 use pocketmine\event\player\PlayerChatEvent;
 use pocketmine\Player;
 use pocketmine\utils\TextFormat;
 use pocketmine\utils\Config;
 use pocketmine\level\sound\AnvilFallSound;
 use pocketmine\entity\Effect;
 use pocketmine\entity\Entity;
 class Main extends PluginBase implements Listener{ public $eco;
 public function onEnable() { $this->getServer()->getPluginManager()->registerEvents($this, $this);
 $this->saveDefaultConfig();
 $config = $this->getConfig();
 $this->eco = $this->getServer()->getPluginManager()->getPlugin("EconomyAPI");
 } public function onChat(PlayerChatEvent $event){ $player = $event->getPlayer();
 $message = $event->getMessage();
 $words = array("ค ุ ว ย", "ส ั ส", "ควย", "ควยย", "ควยยย", "ควยยยย", "ควยยยยย", "กระดอ", "ค ว ย", "ค-ว-ย", "เหี้ย", "เย็ดแม่", "ไอเหี้ย", "พ่อมึงตาย", "สัส", "ไอสัส", "ไอควย", "แม่มึงตาย", "หี", "เซิฟกาก", "แอดมินเป็นเกย์", "พ่อมึงตาย", "ป้ามึงตาย", "ไอรกรวย", "เซิฟเหี้ย", "ควยแอดมิน", "แอดกาก", "กู", "มึง", "fuck", "kuy", "แอดเกย์", "มิคารุกาก", "แม่มึงดิ", "พ่อมึงดิ", "เซิฟควย", "ไอห่านี้", "ไอห่า", "พ่อมึงหรอ", "แม่มึงหรอ", "ไอรเหี้ยแอดมิน", "ไอรสัสแอดมิน", "แอดมินเป็นเกย์", "ไอรแอด", "ไอแอด", "ควยบ้าแอด", "ไอสัสเอ้ย", "ไอเหี้ยเอ้ย", "ควย สัส", "ไม่เล่นละเซิฟนี้", "ขอ op");
 foreach($words as $word){ $pos = strpos(mb_strtolower($message), $word);
 if($pos !== false){ $event->setCancelled();
 $config = $this->getConfig();
 $money = $this->getConfig()->get("money");
 $this->eco->reduceMoney($player, $money);
 $player->sendMessage($this->getConfig()->get("Msg"));
 $player->getLevel()->addSound(new AnvilFallSound($player));
 break;
 } } } }